netz98/n98-magerun2

dev/tests/N98/Magento/Command/Cache/DisableCommandTest.php, dev/tests/N98/Magento/Command/Cache/EnableCommandTest.php, dev/tests/N98/Magento/Command/Cache/ListCommandTest.php, src/N98/Magento/Command/Cache/AbstractModifierCommand.php, src/N98/Magento/Command/Cache/DisableCommand.php, src/N98/Magento/Command/Cache/EnableCommand.php, src/N98/Magento/Command/Cache/ListCommand.php
=> Implementation of cache:list, cache:enable & cache:disable

dev/tests/N98/Magento/Command/Developer/Module/Observer/ListCommandTest.php, dev/tests/N98/Magento/Command/System/InfoCommandTest.php, dev/tests/N98/Magento/Command/System/MaintenanceCommandTest.php, src/N98/Magento/Command/Cache/AbstractModifierCommand.php, src/N98/Magento/Command/Cache/EnableCommand.php, src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php, src/N98/Magento/Command/System/InfoCommand.php, src/N98/Magento/Command/System/MaintenanceCommand.php
=> Work on #119, #118 and #83. Minor fixes for #35 and #36

config.yaml, src/N98/Magento/Command/System/InfoCommand.php
=> update config.yaml with MaintenanceCommand (#83), add vendors to system:info (#118)

.travis.yml
Issue https://github.com/netz98/n98-magerun2/issues/146
=> dropped php5.4 and added php5.6 to .travis.yml

config.yaml, dev/tests/N98/Magento/Command/Admin/User/ListCommandTest.php, src/N98/Magento/Command/Admin/User/AbstractAdminUserCommand.php, src/N98/Magento/Command/Admin/User/ListCommand.php
Issue https://github.com/netz98/n98-magerun2/issues/33
=> ported admin:user:list command

config.yaml, dev/tests/N98/Magento/Command/System/Url/ListCommandTest.php, src/N98/Magento/Command/System/Url/ListCommand.php
Issue https://github.com/netz98/n98-magerun2/issues/127
=> Ported sys:url:list command

config.yaml, src/N98/Magento/Command/Admin/User/ChangePasswordCommand.php
Issue https://github.com/netz98/n98-magerun2/issues/30
=> port admin:user:change-password command

config.yaml, readme.rst, src/N98/Magento/Command/Eav/Attribute/AbstractAttributeCommand.php, src/N98/Magento/Command/Eav/Attribute/ViewCommand.php, tests/N98/Magento/Command/Eav/Attribute/ViewCommandTest.php
* Added abstract attribute command and test
* Added ViewCommand and test
* Logic refactored from Magerun 1 equivalent a little
Covers #101
=> [#101] eav:attribute:view command ported

res/twig/dev/module/create/composer.json.twig
* prefix composer package name with 'module-'
* fix module type to magento2
* add magento2 module autoloader
=> Update composer properties

res/twig/dev/module/create/composer.json.twig
- [n/a] README.md reflects changes (if any)
- Add a trailing slash to the composer.json template (required by Packagist)
=> Add trailing namespace slash (required by Packagist)

.travis.yml, config.yaml
- Add Magento CE 2.0.5
- Add Magento CE 2.0.3
=> Add Magento CE 2.0.3 and 2.0.5

src/N98/Util/Console/Helper/DatabaseHelper.php
Fix mysql cli password parameter
Fixes #194
=> [Fix] db:console password parameter fixed

.travis.yml, config.yaml
=> Add Magento CE 2.0.6

.travis.yml, config.yaml
=> Add Magento CE 2.0.7

readme.rst
- [v ] Pull request against develop branch (if not, just close and create a new one against it)
- [v ] README.md reflects changes (if any)
Fixes # .
- Add Homebrew installation
=> Add Homebrew installation

readme.rst, src/N98/Magento/Application.php, src/N98/Magento/Command/Config/GetCommand.php, src/N98/Magento/Command/Config/SetCommand.php, src/N98/Magento/Command/Database/ConsoleCommand.php, src/N98/Magento/Command/Database/CreateCommand.php, src/N98/Magento/Command/Database/DropCommand.php, src/N98/Magento/Command/Database/DumpCommand.php, src/N98/Magento/Command/Database/ImportCommand.php, src/N98/Magento/Command/Database/InfoCommand.php, src/N98/Magento/Command/Database/QueryCommand.php
Subject: Documentation changes to replace old Magento local.xml file with the new env.php of Magento 2.
=> Replace remaining instances of local.xml with M2 env.php.

CHANGELOG.md, config.yaml, src/N98/Magento/Application.php, src/N98/Magento/Command/AbstractMagentoCommand.php, src/N98/Magento/Command/Database/AbstractDatabaseCommand.php, src/N98/Magento/Command/Database/DumpCommand.php, src/N98/Magento/Command/Database/Maintain/CheckTablesCommand.php, src/N98/Util/Console/Helper/DatabaseHelper.php, tests/N98/Magento/Command/TestCase.php, tests/N98/Magento/TestApplication.php, tests/N98/Magento/TestApplicationTest.php, tests/N98/Util/Console/Helper/DatabaseHelperTest.php
Fixes #239
- Do not strip all order_status* tables
=> Fix sales order status strip, fixes #239

src/N98/Magento/Command/Database/AbstractDatabaseCommand.php, src/N98/Magento/Command/Database/AbstractShowCommand.php, src/N98/Magento/Command/Database/ConsoleCommand.php, src/N98/Magento/Command/Database/CreateCommand.php, src/N98/Magento/Command/Database/DropCommand.php, src/N98/Magento/Command/Database/DumpCommand.php, src/N98/Magento/Command/Database/ImportCommand.php, src/N98/Magento/Command/Database/InfoCommand.php, src/N98/Magento/Command/Database/QueryCommand.php, src/N98/Util/Console/Helper/DatabaseHelper.php
If set, this option allows to select a specific connection database on projects with several databases
=> Adding option --connection for db commands

.travis.yml, config.yaml
=> Add Magento CE 2.1.2

config.yaml, src/N98/Magento/Command/Admin/NotificationsCommand.php, tests/N98/Magento/Command/Admin/NotificationsCommandTest.php
Subject: Porting command: admin:notifications #29
=> Porting command: admin:notifications #29

config.yaml, src/N98/Magento/Command/Design/DemoNoticeCommand.php, tests/N98/Magento/Command/Design/DemoNoticeCommandTest.php
Subject: Port of design:demo-notice command
=> Port of design:demo-notice command

res/twig/dev/module/create/app/code/module/Setup/UpgradeData.php.twig
Subject: Fixes Setup twig template.
Fixes #261  .
- Fix class names
=> Fix class names in Setup twig template.

res/twig/dev/module/create/app/code/module/readme.md.twig
Subject: Fixes minor PHP version in readme to comply to Magento 2 requirements
- Update minor PHP version to 5.6.0
=> Fixes minor PHP version for Magento 2 extensions

.travis.yml, config.yaml, src/N98/Magento/Command/Cache/ReportCommand.php, tests/N98/Magento/Command/Cache/ReportCommandTest.php
Subject: Porting command cache:report, tasks #39
=> Porting command cache:report, tasks #39

config.yaml, src/N98/Magento/Command/Cache/ViewCommand.php, tests/N98/Magento/Command/Cache/ViewCommandTest.php
Subject: Porting of command cache:view, tasks #40
=> Porting of command cache:view, tasks #40

config.yaml, src/N98/Magento/Command/Eav/Attribute/ListCommand.php, tests/N98/Magento/Command/Eav/Attribute/ListCommandTest.php
=> Porting command eav:attribute:list, tasks #99

config.yaml, readme.rst, src/N98/Magento/Command/AbstractMagentoCommand.php, src/N98/Magento/Command/Developer/Asset/ClearCommand.php, tests/N98/Magento/Command/Developer/Asset/ClearCommandTest.php, tests/N98/Magento/Command/Developer/Asset/TestCase.php
Add command dev:asset:clear, tasks #141
Remove duplicate cache:list entry in readme.rst
Subject: Add command dev:asset:clear, tasks #141
=> Add command dev:asset:clear, tasks #141

src/N98/Magento/Command/Database/ImportCommand.php
QuickFixes #290
Sync behaviour with Magerun1
Outlook: Function should be shared across mageruns.
Still it would be great to merge this quickly, as it is a huge performance benefit (and also magerun1 behaves that way)
=> Sync optimize() with Magerun1

.travis.yml, config.yaml
Added 2.1.6, 2.1.7, 2.0.13, 2.0.14
=> Update config with latest Magento 2 releases

src/N98/Magento/Command/Installer/SubCommand/DownloadMagento.php
=> Fix typo in install command

readme.rst
Subject: Fix typo in readme
- Fixes typo in readme
=> Fix typo in readme

config.yaml, readme.rst
Subject: Further improvements to db:dump
Implements feedback provided in #303.
Additional changes proposed in this pull request:
- Add PayPal transaction tables to `@sales` table group
- Add customer log, customer index grid, newsletter subscriptions, product alerts, vaulted tokens and wishlists to `@customer` table group
=> Further improvements to db:dump

config.yaml
=> Add Magento CE 2.1.8 , close 305

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php
Fixes #201 .
- Prevent this error if crontab config does not match with the code base: `[Exception] Notice: Undefined index: name in phar:///var/www/vhosts/score/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php on line 111`
=> Fixes #201

config.yaml, src/N98/Magento/Command/Eav/Attribute/RemoveCommand.php, tests/N98/Magento/Command/Eav/Attribute/RemoveCommandTest.php
Porting command eav:attribute:remove, tasks #100
=> Porting command eav:attribute:remove, tasks #100

.travis.yml, config.yaml
Added Magento 2.2.0, 2.1.9, 2.0.15 and 2.0.14 to the distributed config
=> Add new Magento releases

res/autocompletion/bash/n98-magerun2.phar.bash
Via `bin/compile-bash-autocompletion`.
Refs:
- #327
=> Update bash autocompletion, improves #327

config.yaml
=> #335 Add 2.2.1 + 2.1.10 to install command

config.yaml
- fix version for CE 2.1.10 download
- added downloads for CE 2.1.11 & 2.2.2
=> Fix version for CE 2.1.10 download, added CE 2.1.11 & 2.2.2 downloads

res/twig/dev/console/make/module/composer.json.twig
Add new maximal PHP and Magento Framework requirements for Magento 2.2.
=> Add requirements for Magento 2.2

config.yaml, readme.rst, res/twig/dev/console/make/module/composer.json.twig, src/N98/Magento/Command/Customer/ChangePasswordCommand.php
Adds new command customer:change-password
=> Feature: customer change password

composer.json, composer.lock, src/N98/Magento/Command/Customer/ChangePasswordCommand.php, src/N98/Magento/Command/Customer/CreateCommand.php
Fixes problems with autoloading if no phar file is used.
=> Fixes problems with autoloading if no phar file is used

src/N98/Magento/Command/Cache/CleanCommand.php
Fixes the cache:clean help message.
- It changes the help message in cache:clean help message.
=> cache:clean > fixing help message

readme.rst, src/N98/Magento/Command/Cache/FlushCommand.php
Subject:Flush with types
-    cache:flush now allows a code to be entered like cache:clean or bin/magento cache:flush
=> Flush with types

config.yaml
Fixes incorrect @sessions table group.
=> db:dump - Fix @sessions table group

readme.rst, src/N98/Magento/Command/SelfUpdateCommand.php
Subject: Refactors the self-update command and adds new --dry-run option
=> Add --dry-run mode to self-update command

src/N98/Magento/Command/Database/DumpCommand.php
Fixes #388 
Add check if --add-time option is set in input.
=> Fix #388 Add correct default for --add-time option

src/N98/Magento/Command/System/Cron/RunCommand.php
Fixes #377 
- Add proposed code lines of issue. Load translation part with area model.
=> Fix #377 sys:cron:run - translation is not loaded

config.yaml
Subject: Add magento 2.2.6 and 2.1.15
Fixes #394 .
- Add magento 2.2.6 and 2.1.15
=> Add magento 2.2.6 and 2.1.15

src/N98/Magento/Command/Database/DumpCommand.php
=> Issue #400 Remove PHP warning in db:dump command

.travis.yml, build/travis/script.sh, src/N98/Magento/Command/Customer/ChangePasswordCommand.php, src/N98/Magento/Command/Customer/CreateCommand.php, src/N98/Magento/Command/Developer/Console/AbstractGeneratorCommand.php, tests/N98/Magento/Command/Customer/CreateCommandTest.php, tests/N98/Magento/Command/Developer/Console/MakeCommandCommandTest.php
Update travis test setup.
- Upgrade all Magento versions in test setup to latest versions.
=> Update Magento versions used in travis test setup

src/N98/Magento/Command/Admin/User/ChangePasswordCommand.php, src/N98/Magento/Command/Customer/ChangePasswordCommand.php
Ensures that entered passwords is hidden during input.
Two commands are changed:
- admin:user:change-password
- customer:change-password
=> Hide typed password in password change dialog

src/N98/Magento/Command/Cache/CleanCommand.php, tests/N98/Magento/Command/Cache/CleanCommandTest.php
Subject: cache:clean, add handling of invalid cache types
Fixes #308.
=> #308 - cache:clean, add handling of invalid cache types

src/N98/Magento/Application/MagentoDetector.php
=> Fix for #422 "tilde expansion"

src/N98/Magento/Command/Installer/SubCommand/PostInstallation.php
Subject: fixed reindex command syntax
Fixes #424.
- fixed reindex command syntax
=> fixed reindex command syntax

src/N98/Magento/Command/Config/Data/DiCommand.php
Subject: Unused property
Fixes # N?A
- Code cleanup
=> Unused property

src/N98/Magento/Command/Developer/Console/MakeThemeCommand.php, src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php
Subject: Unused import
Fixes # N/A
- Code cleanup
=> Unused import

src/N98/Magento/Application.php
=> Fix #432: Add method used by newer symfony version

CHANGELOG.md, config.yaml
For table groups referenced when starting w/ @ in config.yaml.
Reference: http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html
Fixes #442
=> Yaml quotes, closes #442

composer.json, src/N98/Magento/Application.php, src/N98/Magento/Application/Magento2Initializer.php
Fixes: Possible warning in Composer Autoloader if phar wrapper is disabled
=> Forbid usage of include-path inside of n98-magerun2

src/N98/Magento/Command/System/Setup/CompareVersionsCommand.php
Since Magento 2.3.0 a module setup version is not a required
settings anymore.
This means, that modules can have a setup version with "null"
as value.
We skip this modules now in our command.
Fixes #450 
- Remove modules without a setup_version in check
=> Issue #450 - Check if module has a setup version

src/N98/Magento/Command/Database/DumpCommand.php
Previously the table structure was still dumped for these tables.
Fixes #412
=> Fix completely exclude tables with --exclude command

config.yaml
=> Fix #439: Add 2fa tables

readme.rst
Script command requires the script command.
- [x ] Pull request against develop branch (if not, just close and create a new one against it)
Small fix for command documentation of the script command.
- readme.rst update
=> Update readme - Script command documentation fix

config.yaml, src/N98/Magento/Command/Admin/Token/CreateCommand.php, src/N98/Magento/Command/Customer/AbstractCustomerCommand.php, src/N98/Magento/Command/Customer/InfoCommand.php, src/N98/Magento/Command/Customer/Token/CreateCommand.php, tests/N98/Magento/Command/Admin/Token/CreateCommandTest.php, tests/N98/Magento/Command/Customer/Token/CreateCommandTest.php
Adds two new command which create api tokens for admin users and customers.
=> Add token create commands for admin and customer

readme.rst, src/N98/Magento/Command/Admin/Token/CreateCommand.php, src/N98/Magento/Command/Customer/Token/CreateCommand.php, tests/N98/Magento/Command/Admin/Token/CreateCommandTest.php, tests/N98/Magento/Command/Customer/Token/CreateCommandTest.php, tests/N98/Magento/TestApplication.php
Add documentation of new commands and a new handling for new-lines after print out of new generated webapi tokens.
=> Optimize token commands

config.yaml
Possible solution for issue #470.
=> Add magento_customercustomattributes_sales_flat... tables

captainhook.json, composer.json, composer.lock, config.yaml
=> Add captainhook and security-advisories

CHANGELOG.md, config.yaml, readme.rst, src/N98/Magento/Command/Developer/ConsoleCommand.php
Closes #497  .
- Add new option `--area` to dev:console command.
=> Feature/497 dev:console area option

README.md
=> Add missing documentation of new integration commands

src/N98/Magento/Application.php, src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php, src/N98/Magento/Command/DummyCommand.php
Subject: Fix broken compatibility check in Magento 2.2 (tested in Magento 2.2.7)
=> Fix compatibility check in Magento 2.2.x

src/N98/Magento/Command/Developer/ConsoleCommand.php
Fixes broken dev:console command
=> Fix broken command if new "area" option is not specified

CHANGELOG.md, README.md, src/N98/Magento/Command/Database/ConsoleCommand.php
#494  - Port db:console command code of n98-magerun2
=> Feature #494 Add mycli support

CHANGELOG.md, src/N98/Magento/Application/ConfigurationLoader.php, tests/N98/Magento/Application/ConfigurationLoaderTest.php, tests/N98/Magento/ApplicationTest.php
After several releases with problems in the configuration loading process, this PR will add integration tests for the dist config and project specific config.
=> Add tests for configruation loader

src/N98/Magento/Application/Console/EventSubscriber/CheckRootUser.php
Fixes #523 
- Fix wrong type hint
=> Fix #523 --skip-root-check throws an error

src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php
Fixes #525 
- Check compatibility only for stable composer versions. Do not check branch names.
=> Bugfix #525 - Check compatibility only for stable versions

CHANGELOG.md, README.md, composer.json, composer.lock, config.yaml, src/N98/Magento/Command/Config/Env/CreateCommand.php, src/N98/Magento/Command/Config/Env/EnvHelper.php, src/N98/Magento/Command/Config/Env/SetCommand.php, src/N98/Magento/Command/Config/Env/ShowCommand.php, tests/N98/Magento/Command/Config/Env/SetCommandTest.php, tests/N98/Magento/Command/Config/Env/ShowCommandTest.php
Subject: New commands to manage **app/etc/env.php** file.
- Add new command config:env:create
- Add new command config:env:set
- Add new command config:env:show
Thanks @peterjaap for providing the main code of `config:env:create` command.
=> Add new config:env commands

src/N98/Magento/Command/Config/Env/SetCommand.php, tests/N98/Magento/Command/Config/Env/SetCommandTest.php
Subject: Check if config:env:set does any changes(important for idempotency)
- Let user know if the configuration has actually changed
- Only write changes when configuration has actually changed
=> Check if config:env:set does any changes

README.md, config.yaml
Subject: Add table groups oauth and klarna and update README.md
- Add table group 'oauth'
- Add table group 'klarna'
- Update table groups description in README.md. It has gotten outdated.
=> Add table groups 'oauth' and 'klarna', update README.md

.travis.yml, config.yaml
=>  Support Magento 2.3.5

.travis.yml
=> Remove failing Magento 2.3.3 from Travis build

config.yaml, src/N98/Magento/Command/System/Check/Env/CacheTypesCheck.php, src/N98/Magento/Command/System/Check/Env/CheckAbstract.php, src/N98/Magento/Command/System/Check/Env/ExistsCheck.php, src/N98/Magento/Command/System/Check/Env/KeyExistsCheck.php, src/N98/Magento/Command/System/Check/Env/MageModeCheck.php, src/N98/Magento/Command/System/Check/Env/XFrameOptionsCheck.php
Subject: Env Checker
Fixes: None.
So this is the pull request about Env Checker that verifies the env.php file and checks if all required keys exist, and if those have correct values (this just checks some of them). I am open to any suggestions, as the official documentation lacks a bit of detailed description of those values, you might have some better ideas to this.
=> [TASK] Env Checker

.github/ISSUE_TEMPLATE/01_bugs.md, .github/ISSUE_TEMPLATE/02_feature_request.md, .github/ISSUE_TEMPLATE/03_enhancement.md, .github/ISSUE_TEMPLATE/04_questions.md, .github/ISSUE_TEMPLATE/05_other.md, .github/ISSUE_TEMPLATE/config.yml
Subject: Template for new Github issues
=> Add Github Issue templates

src/N98/Magento/Command/Database/AbstractShowCommand.php, tests/N98/Magento/Command/Database/StatusCommandTest.php, tests/N98/Magento/Command/Database/VariablesCommandTest.php
Subject: Remove padding for xml, json, csv output
Fixes: Broken tests
=> Fix format if db:status is dumped as CSV

README.md, src/N98/Magento/Command/Customer/CreateCommand.php, tests/N98/Magento/Command/Customer/CreateCommandTest.php
=> #597 Add support for additional fields to customer:create

src/N98/Magento/Command/Config/Store/DeleteCommand.php
=> fixes typo in help

.github/workflows/gitleaks.yml
=> Add gitleaks github workflow

src/N98/Magento/Command/Database/DumpCommand.php
Subject: Correct grammar on db:dump help text
Fixes: *no relevant issue for this change*
- Properly terminate quoted string in 'example' text
- Complete sentence in help text.
=> Correct grammar on db:dump help text

README.md, config.yaml, src/N98/Magento/Command/Cms/ToggleBlockCommand.php
Subject: Command to toggle block status has been added.
Fixes #595.
=> Issue #595: Add a command to toggle the CMS block status

README.md, config.yaml, src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php
Subject: Add command to change admin user status
Fixes #482
=> Issue 482: Add a command to change the admin user status

.travis.yml, src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php, src/N98/Magento/Command/Cms/ToggleBlockCommand.php
Subject: Remove prestissimo composer plugin in Travis build job. Force the use of Composer 2
=> Fix Composer in Travis-CI

.travis.yml, config.yaml
Subject: Add Magento 2.4.1 Open Source
Fixes #658
- Add Magento 2.4.1 to dist config
- Add Magento 2.4.1 to travis-ci
=> Add Magento 2.4.1 Open Source (#658)

README.md, src/N98/Magento/Command/Database/DumpCommand.php, tests/N98/Magento/Command/Database/DumpCommandTest.php
Subject: Adding argument --include to command db:dump
Fixes # .
- Expanding command db:dump by adding argument --include to existing argument --exclude
=> Adding argument --include to command db:dump

.github/workflows/php.yml
=> Set php version to 7.4 in Github actions

composer.json, composer.lock
- Update n98/junit-xml from 1.0.0 to 1.1.0
- Change autoloading from PSR-0 to PSR-4
Ref-Issue: #693
=> Streamline with Ancestor

README.md, src/N98/Magento/Command/Database/DumpCommand.php
Subject: fix readme and set default value
- the shown default options wasn't the same like the actual logic uses
- the readme was the other way around
=> fix readme and set default value

src/N98/Magento/Command/Database/ConsoleCommand.php
Changed config file name to represent Magento 2 config file instead of Magento 1 version.
=> Changed filename where database config comes from.

README.md, config.yaml
Subject: Add mailchimp table group
Not sure how you feel about this (the module not being part of the Magento product), since you said in #547 that you'd like to keep the tool clean. However, it would be great if these tables would not get dumped, as they tend to grow quite large.
- Add table group 'mailchimp'.
- Include table group 'mailchimp' in table group 'trade'. 
- Update README.md
=> Add mailchimp table group

.github/workflows/php.yml, .github/workflows/tests.yml
Add a github action to test phar creation and self-update command
=> Add github action to create a phar and run a self-update

src/N98/Magento/Command/Database/ImportCommand.php
- Properly skip authorization entry creation if the related option is specified
=> Skip authorization creation during db import if option is specified

README.md, config.yaml, src/N98/Magento/Command/Script/Repository/AbstractRepositoryCommand.php, src/N98/Magento/Command/Script/Repository/ScriptLoader.php
Fixes # 819.
Reduce list of folders which are checked for scripts in a project.
=> Optimize script repo performance

src/N98/Magento/Command/Database/ImportCommand.php
Fixes #823
- get stty mode before import
- restore stty mode after import
=> Fix for #823: restore terminal mode after import

README.md, src/N98/Magento/Command/Developer/ConsoleCommand.php, src/N98/Magento/Command/Developer/DevelopmentHelper.php
=> #620 Inject Development Helper () into dev:console

src/N98/Magento/Command/Database/DumpCommand.php
=> Replace the definer instead of trying to remove it

build.sh, composer.json, composer.lock
- Change used composer version in build.sh to v2
- Update abandoned faker dependency to new forked and up-to-date library
=> Update faker dependency and composer in build.sh

.github/workflows/tests.yml
- Add Composer v2 support to github actions
=> Add Composer v2 support to github actions

.github/workflows/tests.yml, config.yaml
- Add Magento 2.4.3 and 2.4.3-p1 to installer
- Add Magento 2.4.3-p1 to test matrix
=> Add Magento 2.4.3 to installer and test pipeline

phpunit.xml.dist, tests/N98/Magento/ApplicationTest.php, tests/N98/Util/FilesystemTest.php
phpunit 9 compatibility changes
=> Dependabot/composer/phpunit/phpunit 9.5.10

phpunit.xml.dist, tests/N98/Magento/ApplicationTest.php, tests/N98/Util/FilesystemTest.php
phpunit 9 compatibility changes
=>  * upd: phpunit 9 compatibility

composer.json, composer.lock, phpunit.xml.dist, tests/N98/Magento/ApplicationTest.php, tests/N98/Util/FilesystemTest.php
=> Deubert it dependabot/composer/phpunit/phpunit 9.5.10

src/N98/Util/Console/Helper/DatabaseHelper.php
Fixes #578  .
As requested in #578, we pass through mysql connection ssl options for both PDO and mysqldump based database interactions.
I was not able to mock or stub the TestApplication in a way without a full magento environment to build a testcase around this. I would appreciate help with setting this up to add test coverage.
This needs testing, so I marked it as experimental. If there are no ssl options set in the environment/db config, behaviour should not be changed at all.
=>  * add: experimental mysql ssl support #578

README.md, src/N98/Magento/Command/ScriptCommand.php, tests/N98/Magento/Command/ScriptCommandTest.php, tests/N98/Magento/Command/_files/test.mr
- Support `${env.VARNAME} style variables in magerun scripts`
=> Add environment variable support in Magerun scripts

src/N98/Util/Console/Helper/DatabaseHelper.php
Fixes #882 .
- Check if host key is available in dbSettings array
=> Fix for #882 "Undefined index: host" error when running db:import

src/N98/Magento/Command/Database/ImportCommand.php
Subject: check if file name was provided for db import command
- before an exception was thrown if a file wasn't existing even if no file name was provided
=> check if file name was provided for db import command

src/N98/Magento/Application.php
Fixes #897
- Add a method which disables the garbage collector of Composer for all Magerun commands
=> Disable Composer gc during Magerun process

src/N98/Magento/Command/Developer/Console/Shell.php
- [ x ] Pull request against develop branch (if not, just close and create a new one against it)
- [ x ] README.md reflects changes (if any)
Subject: (50 characters or less) Added return type for::run()
Potential fix for #509.
- Added return type for::run()
=> Added return type for ::run() #901

.ddev/commands/web/install-magento-ce, .ddev/commands/web/install-magento-ce-git, .ddev/config.yaml, .github/workflows/gitleaks.yml, .github/workflows/linter.yml, .github/workflows/magento_platform_tests.yml, .github/workflows/phar_build_and_update.yml, build.sh, src/N98/Magento/Command/Cache/AbstractModifierCommand.php, src/N98/Magento/Command/Cache/ListCommand.php, src/N98/Magento/Command/System/Check/ResultCollection.php, src/N98/Magento/Command/System/Check/Settings/CheckAbstract.php, src/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstract.php, src/N98/Util/Console/Helper/InjectionHelper.php, src/N98/Util/Console/Helper/Table/Renderer/RendererFactory.php, tests/N98/Util/JUnitSessionTest.php, tests/N98/Util/TimeElapsedTest.php, tests/phar-test.sh
Subject: Compatbility with PHP 8.1 for upcoming Magento release
Fixes #926
- Fix type hints
- Fix return types
- Add test setup for PHP 8.1
- Update locale ddev environment to handle PHP 8.1 Magento projects
- Fix deprecations
- Update 3rd party dependencies
=> PHP 8.1 Compatibility

.github/workflows/magento_platform_tests.yml, src/N98/Magento/Application.php, src/N98/Magento/Application/ConfigLocator.php, src/N98/Magento/Command/Config/Store/GetCommand.php, src/N98/Magento/Command/Database/Execs.php, src/N98/Magento/Command/Installer/SubCommand/InstallMagento.php, src/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstract.php, src/N98/Util/Console/Helper/DatabaseHelper.php, src/N98/Util/ProcessArguments.php
Summary: Fix some deprecation warnings with used strlen
- Replace strlen checks with empty string checks
=> Fix php8.1 deprecations -> strlen checks

README.md
Summary: A tiny readme update
- Remove extraneous single quote in argument listing for "--set-gtid-purged-off"
- Remove extraneous table markers in DB import options table
- Documents the required options for appending the db:dump --add-time option
=> A tiny bit of cleanup

.github/workflows/magento_platform_tests.yml, config.yaml
- Add Mage-OS to Github Actions -> Platform tests
- Add latest Mage-OS version to installable versions in config.yaml
=> Add mage-os to Github actions and installation source

src/N98/Magento/Command/Developer/Module/DetectComposerDependenciesCommand.php
Summary: Mark path argument as required
=> Make path argument required (#954)

.github/workflows/magento_platform_tests.yml
Summary: Update test matrix
- Magento 2.4.4
- Magento 2.4.3-p2
- Magento 2.3.7-p3
=> Test latest Magento versions

.github/workflows/phar_build_and_update.yml, .github/workflows/pr_build.yml, box.json.dist, src/N98/Magento/Application.php
Summary: Add replacement for app name in box config
- Introduce new github action workflow for pull requests generating phar as artifact
- Add a replacement for app name in box.json.dist
- Handle app_name and add a fallback name
=> Dynamically change application name in phar

src/N98/Magento/Command/Config/Store/GetCommand.php
Summary: Fix wrong if condition of scope-id
Fixes #980 
- Fix comparision
=> Fix scope-id condition (#980)

src/N98/Util/Console/Helper/DatabaseHelper.php
Summary: Be less struct if db drop option is used
Fixes #992  .
- Check if database exist in SQL statement (hint by @ktomk)
=> Try to drop only existing databases (#992)

src/N98/Magento/Command/Developer/DevelopmentHelper.php
- [no] README.md reflects changes (if any) [just a fix]
- [?] phar fuctional test (in tests/phar-test.sh)
Fixes #995
=> Fix Customer Debug Functions in Dev Console Dev Helper (closes #995)

src/N98/Magento/Command/Database/Compressor/Uncompressed.php
=> Pass empty string as default value to getFileName

tests/phar-test.sh
Summary: new phar functional tests
- Add tests for dev:console
- Add db:dump test with stdout option
=> additional phar tests

README.md, src/N98/Magento/Command/Config/Store/GetCommand.php, tests/phar-test.sh
Fixes #1023 .
- Fix collection filter condition
- Validate scope option
- Allow the use of scope code via --scope-id option
=> Fix config get scope filter

README.md, config.yaml, src/N98/Magento/Command/Route/ListCommand.php, tests/phar-test.sh
Summary: Add a new command to list routes
Fixes #498
- A new list command to list registered routes
- List routes by area code
- List routes by module name
=> Add route list command

.github/workflows/magento_platform_tests.yml, config.yaml
Summary: Add Magento 2.4.5-p1 / 2.4.4-p2
Fixes # .
- Add Magento 2.4.5-p1 / 2.4.4-p2
- Update tested versions in GitHub Actions to only test the latest patch version
=> Magento 2.4.5-p1 / 2.4.4-p2

src/N98/Magento/Command/Indexer/AbstractIndexerCommand.php, src/N98/Magento/Command/Indexer/ListCommand.php, src/N98/Magento/Command/Indexer/RecreateTriggersCommand.php
Seems that this command is really outdated. The command contained very old code.
Fixes #1066
- Remove old M1 logic which never works in M2
- Add last_update column in `index:list` output
=> Fix broken index:list command (issue #1066)

.github/workflows/magento_platform_tests.yml, README.md, src/N98/Magento/Command/AbstractMagentoStoreConfigCommand.php, src/N98/Magento/Command/Cache/CleanCommand.php, src/N98/Magento/Command/Customer/ListCommand.php, src/N98/Magento/Command/Database/Maintain/CheckTablesCommand.php, src/N98/Magento/Command/Developer/Console/AbstractGeneratorCommand.php, src/N98/Magento/Command/Indexer/RecreateTriggersCommand.php, src/N98/Magento/Command/System/Cron/HistoryCommand.php, src/N98/Magento/Command/System/Cron/ListCommand.php, src/N98/Magento/Command/System/Cron/RunCommand.php, src/N98/Magento/Command/System/Cron/ScheduleCommand.php, src/N98/Magento/Command/System/Setup/ChangeVersionCommand.php, src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php, src/N98/Magento/Command/System/Store/Config/BaseUrlListCommand.php, src/N98/Magento/Command/System/Store/ListCommand.php, src/N98/Magento/Command/System/Url/ListCommand.php, src/N98/Magento/Command/System/Website/ListCommand.php
- Update compatibility infos in README
- Add missing `Command::SUCCESS` and `Command::FAILURE` returns in Symfony Commands.
=> Fix command returns

src/N98/Magento/Command/Developer/ConsoleCommand.php
Summary: Supress psysh user warning
=> Prevent output of notice if history file cannot load written (#1096)

CHANGELOG.md, README.md, config.yaml, src/N98/Magento/Command/Config/Data/IndexerCommand.php, tests/phar-test.sh
Summary: Add new command `config:data:indexer`
Implements #1041
=> config:data:indexer command to print merged indexer.xml data

CHANGELOG.md, README.md, config.yaml, src/N98/Magento/Command/Config/Data/IndexerCommand.php, src/N98/Magento/Command/Config/Data/MViewCommand.php, tests/phar-test.sh
Summary: New command `config:data:mview`
Implements #1042
=> New command config:data:mview

CHANGELOG.md, src/N98/Magento/Command/SearchEngine/ListCommand.php
- Remove empty entry in list of search engines
=> Remove "please select" entry in search:engine:list command

src/N98/Util/Console/Helper/MagentoHelper.php
Summary: Just add some more debug output for Magento detection
Background: was having a incomplete Magento install and wondering how Magento detection is working. I used xdebug :-) This debug output should avoid the need for that
=> Make detection debug output more helpful

src/N98/Magento/Application/Config.php, src/N98/Magento/Application/ConfigurationLoader.php
- Allow the registration of PSR-4 namespaces as array item
Override existing or define a new namespace:
```yaml
autoloaders_psr4:
Acme\Foo: %module%/src
```
Append directory for existing namespace
```yaml
autoloaders_psr4:
- Acme\Foo: %module%/src
```
=> Allow to add instead of replace a PSR-4 namespace (#1144)

src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php, tests/phar-test.sh
Fixes #1147
- Return a status code
- Add handling for the right status if any module downgrade fails
- Add functional phar test for command
=> Fix command return value and add phar test (#1147)

src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php
- Skip Magento Core Command in Magerun Compatibility check
- Skip the install and self-update command in check (it's not Magento related)
=> Do less compatibility checks

src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php
Fixes #1206 
- Check for `null` value of target version.
=> If no target version is available do not do a version_compare

src/N98/Magento/Command/ScriptCommand.php
- [ x ] Pull request against develop branch (if not, just close and create a new one against it)
- [ NA ] README.md reflects changes (if any)
- [  ] phar fuctional test (in tests/phar-test.sh)
Fixes #1223.
Not sure how to write the test for this, please let me know if required and what the test should look like.
- Pass no-interaction flag to child commands if set on parent Magerun command
=> Pass the no-interaction flag to child commands

CHANGELOG.md, src/N98/Magento/Command/Route/ActionPathFormatter.php, src/N98/Magento/Command/Route/ListCommand.php, tests/N98/Magento/Command/Route/ActionPathFormatterTest.php, tests/phar-test.sh
Summary: Do some first smaller refactoring of this very complex class
- Add action path formatter with test
- Split logic into methods
=> First refactoring of route:list command

README.md
=> Add missing docs for cache:view, cache:report (#1253)

README.md, config.yaml, src/N98/Magento/Command/Cache/RemoveIdCommand.php, tests/bats/functional_magerun_commands.bats
Summary: Adds a new command to remove a entry from cache by passing the ID.
Fixes #496
=> New command cache:remove:id

.github/workflows/linter.yml, .github/workflows/magento_platform_tests.yml, src/N98/Magento/Command/Installer/SubCommand/DownloadMagento.php
Related to #989.
- Do the credential check only for repository-urls containing repo.magento.com
=> Ask only for credentials if repo.magento.com is used

.ddev/commands/web/install-mage-os, src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php
- Add new ddev command `install-mage-os` for test setup
- Fix compatibility check
=> Mage-OS ddev setup

src/N98/Magento/Command/Route/ListCommand.php
Related to #1304
- Add the proposed filter from reporter to filter action classes (filter abstract classes)
=> Filter non action classes in route:list output (#1304)

CHANGELOG.md, README.md, config.yaml, src/N98/Magento/Command/Config/SearchCommand.php, tests/bats/functional_magerun_commands.bats
Provides  #51
- Add new command to search in store config
=> config:search Command

README.md
Humble contribution.
`README.md`: converting two spaces to a single one.
=> README.md - two spaces converted to one

README.md, config.yaml, src/N98/Magento/Command/Developer/DecryptCommand.php, src/N98/Magento/Command/Developer/EncryptCommand.php, tests/bats/functional_magerun_commands.bats
Added an encrypt and decrypt command to easily debug encrypted values, and even be able to update encrypted value
=> Add encrypt and decrypt commands

README.md, src/N98/Magento/Command/Integration/CreateCommand.php, tests/bats/functional_magerun_commands.bats
Related to #1441
- Mark email and endpoint url as optional arguments
- Add functional test for reduced argument list
- Update docs -> README.md
=> Call integration:create with name only

.github/workflows/magento_platform_tests.yml, config.yaml
=> Add new Magento Versions (2.4.7, 2.4.6-p5, 2.4.5-p7, 2.4.4-p8)

src/N98/Magento/Command/Route/ListCommand.php, tests/bats/functional_core_commands.bats, tests/bats/functional_magerun_commands.bats
Related to #1411
- Check if action class implements any of the action interfaces related to http method
- Move bats tests from core to magerun suite
=> Add HTTP methods to route list

.github/workflows/phar_build_and_update.yml, .github/workflows/php_compatibility.yml, README.md, src/N98/Magento/Command/SelfUpdateCommand.php
- Add new argument to self-update command to define a specific version
=> add: new version argument to update to specific version

CHANGELOG.md
=> Fix Hyvä command name

config.yaml, src/N98/Magento/Application.php, src/N98/Magento/Application/ConfigFile.php, src/N98/Magento/Application/ConfigInfo.php, src/N98/Magento/Application/ConfigurationLoader.php, src/N98/Magento/Command/Magerun/ConfigDumpCommand.php, src/N98/Magento/Command/Magerun/ConfigInfoCommand.php, src/N98/Util/Console/Helper/MagentoHelper.php, tests/bats/functional_magerun_commands.bats
Summary: New commands to dump and verify the Magerun configuration
Fixes #1595 
- Add the command `magerun:config:dump`
- Add the command `magerun:config:info`
=> magerun config commands

src/N98/Magento/Command/Developer/Theme/BuildHyvaThemeCommand.php
=> fix: theme choice index

src/N98/Magento/Command/Customer/AddAddressCommand.php
Possibly fixes #1616.
- Create address in store emulated area
=> fix: run create address in a emulated frontend area

.github/workflows/phar_build_and_update.yml, composer.json, composer.lock, src/N98/Magento/Application.php, src/N98/Magento/Command/AbstractMagentoCommand.php, src/N98/Magento/Command/Customer/DeleteCommand.php, src/N98/Magento/Command/Database/AbstractDatabaseCommand.php, src/N98/Magento/Command/Database/DumpCommand.php, src/N98/Magento/Command/SelfUpdateCommand.php, src/N98/Util/Console/Helper/CommandTrait.php, src/N98/Util/Console/Helper/MagentoHelper.php, src/N98/Util/Console/Helper/ParameterHelper.php, src/N98/Util/Console/Helper/TwigHelper.php, src/N98/Util/Validator/FakeMetadataFactory.php
Fixes #1596
- Update all Symfony components to 6.4 LTS
- Increase minimum PHP version to 8.1
- Refactoring of all Helpers, Commands and the main Symfony Application
=> feat: update to symfony 6.4

.github/workflows/magento_platform_tests.yml, tests/bats/functional_magerun_commands.bats
Split bigger bats tests into smaller ones to quickly recognize broken tests.
=> split magerun bats functional tests

docs/docs/extending/development/add-custom-commands.md
- Describe the `inject` method
- More examples
- Describe important methods of the abstract parent class
=> Extend command docs

.github/scraper/.gitignore, .github/scraper/magerun_docs_config.template.json, .github/workflows/docs-scaper.yml, .gitignore
Workflow to run a scaper for docs search
=> docs scaper Github Workflow

README.md, docs/docs/command-docs/composer/composer-redeploy-base-packages.md, docs/docs/command-docs/composer/index.md, docs/docs/extending/extend-composer-redeploy-base-packages-command.md
- Add the missing documentation for the composer commands
- Explain how the command can be extended
=> add documentation for composer:redeploy-base-packages command
