src/N98/Magento/Command/Developer/Module/Create/SubCommand/CreateComposerFile.php

As per #157 the `CreateModuleFolders` class defines the config string as `moduleDirectory`:
```
$this->config->setString('moduleDirectory', $moduleDir);
```
Updated in the `CreateComposerFile.php` class.

[#157] Changed moduleFolder to moduleDirectory

---

.travis.yml
build/travis/mysql-5.6-install.sh

Installing of Mysql 5.6 for Magento 2 failed recently. Fix for that in this PR.
Additionally composer moans about xdebug being enabled and rightly so! As xdebug is not used any longer for the build, it's safe to disable which is done with this PR.

Update Travis build

---

config.yaml
readme.rst
src/N98/Magento/Command/GiftCard/AbstractGiftCardCommand.php
src/N98/Magento/Command/GiftCard/CreateCommand.php
src/N98/Magento/Command/GiftCard/InfoCommand.php
src/N98/Magento/Command/GiftCard/Pool/GenerateCommand.php
src/N98/Magento/Command/GiftCard/RemoveCommand.php

Covers #132 #133  #134:
* Ported `giftcard:create`
* Ported `giftcard:info`
* Ported `giftcard:remove`
* Ported `giftcard:pool:generate` (not "issued" yet)
* Updated readme
* Added optional expiration date to `giftcard:create`
NOTE: The `setAdminArea()` method in the AbstractGiftCardCommand is probably more general than just for gift cards. I was experiencing exceptions like "Area not set" etc being thrown from Magento framework when trying to load a giftcard model. It's reported through the Magento binary tool on their GitHub repository also, but this works for now.

[#132] Ported Giftcard commands

---

config.yaml
readme.rst
src/N98/Magento/Command/System/Setup/AbstractSetupCommand.php
src/N98/Magento/Command/System/Setup/ChangeVersionCommand.php
src/N98/Magento/Command/System/Setup/CompareVersionsCommand.php
tests/N98/Magento/Command/System/Setup/AbstractSetupCommandTest.php
tests/N98/Magento/Command/System/Setup/ChangeVersionCommandTest.php
tests/N98/Magento/Command/System/Setup/CompareVersionsCommandTest.php

Resolved #120.
Changes:
* Ported sys:setup:change-version command
* Updated references to M1 framework for M2 in abstract command
* Added unit tests
Notes:
* I've removed the setup argument as it appears that Magento 2 has removed the granularity of different setup resources.
* ~~I've removed the inject() method use in favour of mockable getters (although it pained me to do it)~~ Update: left in place, using getters as well for mocking
* ~~The tests that mock the command classes need to be run in isolation, otherwise the following error is thrown: `PHP Fatal error:  Call to undefined method Magento\Framework\Module\ModuleList::getNames() in [.../]src/vendor/magento/framework/Module/DependencyChecker.php on line 50`~~ Not required any longer.

[#120] Ported sys:setup:change-version command

---

src/N98/Magento/Application.php

If the Application's reinit method is called the $this->init($initConfig, $input, $output); throws an UnexpectedValueException (Config already initialized)
because the $this->config variable is still set
this fix just resets $this->config
Found the issue while trying to install magento2.0.2 from command line via: docker exec -it magento2demo_app_1 bin/n98-magerun2 install \
--useDefaultConfigParams=yes --installationFolder="." \
--dbHost=mysql --dbUser=magento --dbPass=magento --dbName=magento \
--baseUrl=http://magento2.local/ --noDownload --forceUseDb=true

[BUGFIX] Bugfx in reinit to prevent "Config already initialized"

---

src/N98/Magento/Command/System/Cron/RunCommand.php

While this may seem nonstandard, there is actually some Enterprise code that encourages this pattern. The execution of ``call_usr_func_array`` is wrapped in a try/catch, so I don't think this should pose any issues.

Allow crons to run from __call

---

src/N98/Magento/Command/System/Cron/RunCommand.php

Following up from discussion in PR #192 
This is the proper way to emulate cron state. I don't think it is doing anything different than the current implementation, just changing area code, but still -- might as well use the standardized emulation method. Found this out from magento/magento2#4393

Properly emulate cron app state

---

src/N98/Magento/Command/Developer/TemplateHintsCommand.php

Subject: Update template-hints config value
Fixes #230 
- Propose changing config path for toggling template hints to `template_hints_storefront` ~~because it has changed to this in version 2.1, and thus breaks at that version. I am currently basing this on 2.1.0-rc3, so I guess this change might best wait until formal release.~~
Also, I think that a new command may need to be added for toggling admin panel hints as that's now a separate config and can no longer be specified as a store via `dev:template-hints`.

Update template hints config value

---

src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php

Subject: Added support for more areas in the observer list
Fixes #249
These area's exist in all current versions of Magento: 2.0.0 through 2.1.2
Recently the 'admin' area has been deprecated (this hasn't been released in a tagged version though).

Added support for more areas in the observer list

---

tests/N98/Magento/Command/Database/VariablesCommandTest.php

Subject: Fix failing VariablesCommandTest for MariaDB 10.1.19
- Fixes failing VariablesCommandTest for MariaDB 10.1.19
<pre>
1) N98\Magento\Command\Database\VariablesCommandTest::testRounding
Failed asserting that '"Variable Name",Value
aria_block_size,"  8.00K"
[---snip---]
myisam_max_sort_file_size," 10.00G"
[---snip---]
wsrep_max_ws_size,"  2.00G"
' matches PCRE pattern "~myisam_max_sort_file_size,"  [0-9\.]+[A-Z]"~".
</pre>

Fix failing VariablesCommandTest for MariaDB 10.1.19

---

config.yaml
src/N98/Magento/Command/System/Cron/AbstractCronCommand.php
src/N98/Magento/Command/System/Cron/HistoryCommand.php
src/N98/Magento/Command/System/Cron/ListCommand.php
src/N98/Magento/Command/System/Cron/RunCommand.php
src/N98/Magento/Command/System/Cron/ScheduleCommand.php
src/N98/Magento/Command/System/Store/ListCommand.php
src/N98/Magento/Command/System/Website/ListCommand.php
tests/N98/Magento/Command/System/Cron/ScheduleCommandTest.php

Sometimes we want to run a cronjob, but not keep our ssh session or terminal open while running `sys:cron:run`. This PR adds a `sys:cron:schedule` command which schedules a certain job in the cron schedule to be executed the next time the cron is being run.
Was inspired by the excellent [Aoe_Scheduler module](https://github.com/AOEpeople/Aoe_Scheduler) for M1.
Possible discussion points:
1) The name `schedule` might be confusing, people might expect they can provide a timestamp on which time they want to schedule a job. Is this wanted? We could also name the command `schedule-now` or something like that?
2) I copied a lot of code from the `RunCommand` class. This should definitely be refactored away. Should we put shared code in the `AbstractCronCommand` …

Added sys:cron:schedule command

---

readme.rst
src/N98/Magento/Command/Installer/SubCommand/PreCheckPhp.php

Magerun now gives an error when xdebug.max_nesting_level is set to `-1`, which is a valid value meaning "no maximum".
```
$ n98-magerun2.phar install
Magento 2 Installation
[RuntimeException]
Please change PHP ini setting "xdebug.max_nesting_level". Please change it to a value >= 200. Your current value is -1
```

Allow -1 as value for infinite max nesting level for xdebug

---

src/N98/Magento/Command/System/Cron/ScheduleCommand.php

----
After upgrading magerun2 from version 1.3.2 to 1.3.3, and running the command:
`sys:cron:schedule some-cronjob`, we get the error:
```
[Magento\Framework\Exception\SessionException]
Area code not set: Area code must be set before starting a session.
[Magento\Framework\Exception\LocalizedException]
Area code is not set
```
This problem was recently introduced by https://github.com/netz98/n98-magerun2/commit/64063ae6f91ee764993e7c6b2e953c66a51fcdd0 & https://github.com/netz98/n98-magerun2/commit/a50f3b75ae13eda8488a82cd308f9062fd483892
Fixing it by using the same workaround as in https://github.com/netz98/n98-magerun2/commit/64063ae6f91ee764993e7c6b2e953c66a51fcdd0
Not sure if all the code is needed though, only the first line already solves the …

Fixes sys:cron:schedule 'area code is not set' exception.

---

src/N98/Magento/Command/System/Cron/RunCommand.php

When running sys:cron:run, if the job fails, there is no exception displayed and you simply get "done".
This is in contrast to n98-magerun for Magento 1 which displays an exception.
I've ported over the same exception reporting code from n98-magerun to n98-magerun2, but I'm happy to take feedback on different/better way to handle the exception reporting.
To reproduce:
- Modify `app/code/Magento/Sales/Cron/CleanExpiredQuotes.php` and add `throw new Exception('TEST');` to the first line of `execute()`
- Run `sys:cron:run sales_clean_quotes`
What happens:
You see `Run Magento\Sales\Cron\CleanExpiredQuotes::execute done`
Expected:
An exception reported to console, which displays a stack trace when the command line was `sys:cron:run sales_clean_quotes -v`

Display exception if cron job fails in sys:cron:run

---

src/N98/Magento/Command/Developer/Console/Shell.php

Hello!
This issue is fairly easy to reproduce. Just enter dev:console and try some of the following:
`a::b()`
Expects: PHP Fatal error: Class 'a' not found in eval()'d code on line 1
Actual: Nothing
`json_decode(array(), true)`
Expects: PHP warning:  json_decode() expects parameter 1 to be string, array given on line 1
Actual: Nothing
It makes for quite strenuous debugging! After some time I tracked it down to the N98 Shell writeException not printing the exception. This Pull Request makes sure that if writeException isn't handling the exception in some way, it prints it out.
Thanks!

Prevent exceptions in dev:console from being suppressed and hidden

---

src/N98/Magento/Command/Database/DumpCommand.php
tests/N98/Magento/Command/Database/DumpCommandTest.php

**Magerun pull-request check-list:**
**Subject: (50 characters or less)**
Port db:dump `--exclude` command from magerun 1
https://github.com/netz98/n98-magerun/commit/18e7d9e49d91c4b4a1735682d8f324591fd0fdf0
https://github.com/netz98/n98-magerun/issues/616
**Changes proposed in this pull request:**
Pass in `--exclude="..."` options with db:dump command to exclude table structure and data
Example
```bash
$n98-magerun2 db:dump --exclude="core_config_data"
```

Port db:dump --exclude from magerun 1

---

config.yaml
readme.rst
src/N98/Magento/Command/Database/DumpCommand.php

Subject: Improve db:dump (documentation & table groups)
Fixes #248.
- Add documentation for `db:dump` (largely copied from M1 version) and tweak `--help` wording
- Add new `@quotes` table group and then include this group in `@trade`
- Add missing tables to `@sales` table group (invoices, shipments & credit memos)
- Add `customer_visitor` table to `@customers`

Improve db:dump (documentation & table groups)

---

config.yaml
readme.rst

Subject: Strip Admin Users In Development DB Dump
For security purposes, it's better to strip `admin*` and `authorization*` when dumping a production database for non-production use. For example, the production database could be restored to staging with production admin user data. The staging environment may not have the same level of security as production (e.g. default admin route, not rate limiting brute force password guessing). An attacker could leverage the staging environment to identify production user credentials and then use them to obtain access to the production system.
- `admin*` and `authorization*` are stripped when running a development db dump
If the maintainers agree with this change, I can …

Strip Admin Users In Development DB Dump

---

config.yaml
src/N98/Magento/Command/Installer/SubCommand/CreateDatabase.php
src/N98/Magento/Command/Installer/SubCommand/InstallMagento.php
src/N98/Magento/Command/Installer/SubCommand/InstallSampleData.php

* Adds DB default settings in the installation config (host, port, user and db name). It's possible to use the `%s` placeholder in DB name config setting that will be replaced with the installation folder base name.
* Adds default base URL setting in the installation config and like the DB name it's possible to use the `%s` placeholder that will be replaced with the installation folder base name.
* Adds the boolean sample data setting in the installation config to specify whether to install sample data or not by default.
With these changes it's possible to run an unattended installation with:
n98-magerun2.phar install -n --magentoVersionByName="magento-ce-2.2.0" --installationFolder="myproject"
Or with:
n98-magerun2.phar install -n --noDownload …

Provides more config values for install command

---

src/N98/Magento/Command/Generation/FlushCommand.php

Fixes broken generation:flush command in Magento 2.2

Add support for Magento 2.2 for generation:flush command

---

tests/N98/Magento/Command/Script/Repository/ListCommandTest.php
tests/N98/Magento/Command/Script/Repository/RunCommandTest.php
tests/N98/Magento/Command/ScriptCommandTest.php
tests/N98/Util/ExecTest.php

Re-Enable skipped tests. The tests are skipped because of some memory issues in travis build jobs. The tests are now running in separated processes. So the issue should be fixed for the travis build.

Remove "exclude-2.2" group annotation to re-enable skipped tests

---

build/circleci/source.sh

Fixes broken Circle-CI build.
Increased the Magento Version from 2.0.0 to 2.2.0.

Change Magento Version for Circle-CI Build to 2.2

---

src/N98/Magento/Command/Installer/SubCommand/DownloadMagento.php

- [x ] Pull request against develop branch (if not, just close and create a new one against it)
- [x ] README.md reflects changes (if any)
Subject: Magento Keys
The Magento Keys (needed for installation) are no longer found under magentocommerce.com but in the Marketplace instead. This pull request changes the link during installation.
- ...

Magento keys are now found in Magento Marketplace

---

src/N98/Magento/Command/System/InfoCommand.php

Add "root" directory to sys:info command. This is useful to use the auto-root detection of n98-magerun in bash scripts.

Add Magento-Root to sys:info command

---

src/N98/Magento/Command/Script/Repository/ScriptLoader.php

**Subject**: Optimise the runtime of script:repo commands
**Fixes** # Scanning for magerun scripts taking too long when scanning the media files on EFS filesystems
**Changes proposed in this pull request:**
**Problem description:**
The command `n98-magerun2 script:repo:list`
is running for 10 to 30 minutes before showing the expected result.
**To reproduce the situation:**
A large “pub/media” folder having thousands of directories containing many files.
If the filesystem is slow (eg, using NFS or a slow disk), the problem will be worse.
When debugging the command I found that the `findScriptFiles()` function will the whole magneto folder and the magerun config paths.
Accessing many files on NFS can be very slow so that it takes 10 to 30 minutes depending on the size of the media folder. …

Optimise the runtime of script:repo commands

---

config.yaml

Stripping of authorization* tables stops the creation of user roles as there is no Administrators role - this reverts the stripping of authorization*

unstripping authorization*

---

config.yaml

Improve db:dump command.
`db:dump --strip="@search"` should drop `search_query` and `search_synonym` tables as well.
Fixes #354

Added additional tables to "search" table-group, fixes #354.

---

src/N98/Magento/Command/AbstractMagentoStoreConfigCommand.php

Fixes #333
Use the new "config:store:set" command instead of the "config:set" command.

Fix issue #333 - dev:template-hints not working with Magento 2.2.0

---

src/N98/Magento/Command/Installer/InstallCommand.php
src/N98/Magento/Command/Installer/SubCommand/DownloadMagento.php
src/N98/Magento/Command/Installer/SubCommand/InstallComposer.php
src/N98/Magento/Command/Installer/SubCommand/InstallComposerPackages.php
src/N98/Util/OperatingSystem.php
src/N98/Util/WindowsSystem.php

By supplying the --composer-use-same-php-binary option to the install command n98-magerun2 will invoke Composer with the same PHP binary n98-magerun2 was invoked. Fixes #295.

Add option to force Composer to use same PHP binary as n98-magerun2 was invoked with

---

config.yaml

Fixed table-group @customer for command db:dump with option --strip
Affected Tables which are now also only being exported as structure without data:
* 'customer_entity' and all child eav tables
* 'vault_payment_token' and 'vault_payment_token_order_payment_link'
* 'wishlist' and all child item tables
The problem was that the wildcard p.e. 'customer_entity*' doesn't match 'customer_entity' itself.
Wildcard substitutions were being added to cover that.
Fixes # .
- ...
- ...
- ...

[BUGFIX] db:dump fixed table-group @customer

---

config.yaml
readme.rst

Hi,
This PR adds the company tables (from the B2B Commerce extension) to the `@customers` table groups. 
I've added this to `@customers` because the company_* tables are related with the customers.
This should prevent the  `No such entity with customerId = X` error when opening a company in the backend when using a DB dump with the customer data stripped.
Please let me know if something has to be done before this can be merged. 
Thanks!

Add company table to @customer table group

---

config.yaml
readme.rst

Strip dotmailer tables which comes bundled with Magento because it might contain customer-sensitive data (the email address) for tables email_abandoned_cart email_automation email_campaign email_contact.
Fixes #380 .
- add dotmailer group
- dotmailer group will include (email_abandoned_cart email_automation email_campaign email_contact) tables
Please let me know if there is more to check/change for this PR.

db:dump strip=@stripped does not strip sensitive data

---

readme.rst

Subject: Remove homebrew installation from readme
I think currently it's not possible to install n98-magerun2 with homebrew.
The Homebrew/php tap was archived on 31st March 2018.
```
$ brew search magerun
No formula or cask found for "magerun".
```
- Remove homebrew installation from readme

Homebrew php tap is deprecated

---

src/N98/Magento/Command/System/Cron/RunCommand.php

Subject: Not using Emulation-Mode in on RunCommand
Fixes #245 
- Thanks to #377 , it is not needed to start command in emulation mode
Issue-Description:
In #277, emulation mode was introduced for command. But if you use another `startEmulationMode`/`emulateAreaCode` with empty cache, the error
> Required parameter 'theme_dir' was not passed
still exists. The Problem is, that the started emulation mode in RunCommand set `isAreaCodeEmulated` to `true` and on `startEmulationMode`, Magento tries to load a theme in crontab-scope (see `\Magento\Theme\Model\Theme::getArea`), which throws the Exception in `\Magento\Framework\View\Design\Fallback\Rule\Simple::getPatternDirs`.
If there is a cache, it works in case, you have …

Emulation-Mode not needed after set current area. This resolves #245

---

config.yaml

Subject: Additional enterprise-only tables missing from the table group configuration
The enterprise RMA table includes customer emails and could easily be overlooked by someone trusting the @development group to remove all PII.

Additional enterprise-only tables missing from the table group configuration

---

src/N98/Magento/Command/Database/DumpCommand.php

Check if filename is passed. If not, do not try to use it.
Fixes #401

Fix #401 - warning in db:dump command with --stdout

---

src/N98/Magento/Application.php
src/N98/Magento/Command/Installer/SubCommand/DownloadMagento.php
src/N98/Util/Console/Helper/MagentoHelper.php

This PR removes the hardcoded `app/etc` path in the following components/commands:
- The `checkVarDir` method of the main `Application`
- The `DownloadMagento` subcommand
- The base configuration loading inside the `MagentoHelper`

Uses Magento's DirectoryList to get config folder path (app/etc)

---

src/N98/Magento/Command/Customer/CreateCommand.php

Fixes # store_id and created_in value in customer_entity when create customer by n98 command
- Change default store group id by default store id

Fix create customer store id

---

src/N98/Util/Console/Helper/ParameterHelper.php

Subject: Fix count on non-countable variable for php 7.2 compatibility
- Calling `count` on a variable with a `null` value produces a warning in PHP 7.2

Fix count on non-countable variable for php 7.2 compatibility

---

composer.json
composer.lock
src/N98/Magento/Application/Magento2Initializer.php

Magento 2.3.1 removes the phar stream wrapper in the app/bootstrap.php.
We re-enable the phar wrapper even after loading the bootstrap.
Fixes problem with bootstrap.php in Magento 2.3.1 which removes the phar stream wrapper.

Add phar wrapper for Magento 2.3.1 compatibility

---

build.sh

Subject: make build.sh OSX compatible
- use perl instead of awk b/c awk w/ OSX does not support gensub (requires gawk)
also more readable in perl (IMO)
- test for OSX before attempting to set ulimit

make build.sh OSX compatible

---

src/N98/Magento/Command/Database/DumpCommand.php

Subject: Fix db:dump while using option "-t" instead of "--add-time"
- Use `getOption` instead of `hasParameterOption ` so you can use the shortcut for 'add-time'

Fix db:dump while using option "-t" instead of "--add-time"

---

config.yaml

Similiar to [n98-magerun issue](https://github.com/netz98/n98-magerun/issues/1016): it would be great if n98-magerun2 checks with /usr/share/n98-magerun2/modules directory for packaged plugins first.

Extra directory for plugins

---

src/N98/Magento/Command/Database/DumpCommand.php
src/N98/Util/Exec.php

Pipe commands are not handled correct.
The db:dump command will always return "0" which means "correct" even if an error occurs.

Fix error status for executed commmands in a pipe

---

src/N98/Util/Exec.php
src/N98/Util/OperatingSystem.php

If current shell does not support pipefail option, all exec calls are broken.

Check if pipefail option exists

---

composer.json

Adds a suggest entry in composer.json which provides a hint to use the phar dist package.

Add "suggest" to use the phar distribution

---

src/N98/Magento/Command/Admin/User/AbstractAdminUserCommand.php
src/N98/Magento/Command/Admin/User/ChangePasswordCommand.php

Fix for issue #293
Call the track method after a password change. Normally a changed password will automatically tracked by an observer in adminhtml area.
This will not clear the session for a already authenticated user. A user need to logout and login again after a successful password change.

Track changed admin passwords

---

config.yaml

Subject: Add table groups
Add following table groups:
- aggregated
- newrelic_reporting
- replica
These tables can grow quite big and saves plenty of importing time when you don't dump their data. Also, these tables contain generated/analytic content, which aren't necessary in many environments.

Add table groups

---

composer.json
composer.lock

Packages with uppercase characters are invalid for Composer 2.0
Fixes: Invalid composer.json

Fix composer package naming

---

config.yaml
readme.rst

- Also strip `negotiable_quote` and associated tables as part of `@quotes` alias. These come from the B2B module and should not be included in development databases.

Strip B2B quotes as part of @quotes alias

---

.travis.yml

- Enable PHP 7.3 for latest Magento 2.3.3 version. Run tests against Magento 2.3.3

Enable tests with PHP 7.3

---

CHANGELOG.md
src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php

Since Magento 2.3.0 the "getVersion" and "getDataVersion" method is thowing an BadMethodCall exception if there is no version available.
Fixes #487

Fix #487 broken downgrade versions command

---

CHANGELOG.md
src/N98/Magento/Application/ConfigurationLoader.php

Fixes #516
- Load config file instead of passing file name to Yaml::parse method. This was possible in old Symfony library version.

Fix #516 4.0.0: Fatal error when /etc/n98-magerun2.yaml exists

---

README.md

- [ v] Pull request against develop branch (if not, just close and create a new one against it)
- [ v] README.md reflects changes (if any)
Improved README.md, quite some syntax needed to be fixed caused by conversion from RST to Markdown in  2c546583a7035a1c350183209b69ff9b79bdef40
- Improve README.md syntax

Improved README markdown syntax

---

src/N98/Magento/Application/ConfigurationLoader.php

ConfigurationLoader.php::loadProjectConfig..
After recent refactoring, `$projectConfig` changed from `null` instanciated to `[]`.
The corresponding check in `loadProjectConfig` changed to a `!== null` to `empty()`.
This is opposite of the previous functionality and prevented the projectConfig from being loaded, (because `$projectConfig` always starts off empty).
Ref: https://github.com/netz98/n98-magerun2/commit/e80ab373b7c67c14b238cd194a5cd7c5a95bfe4d#r36645773

Fix loading `app/etc/n98-magerun.yaml`

---

src/N98/Magento/Application/ConfigLocator.php

For discussion / inclusion.
Subject: A home directory that doesn't exist isn't a fatal error
- Currently, if $HOME points somewhere that isn't a directory, Magerun throws a RunTime exception.
This would make sense if it relied on information coming from the home directory was required, but it's very much optional.
Rather than die, just act as if nothing was set.
Unsure as to the exact intent of the exception, so this is a request for feedback as much as a proposal for change.

If the discovered home directory does not exist - don't try and use it

---

config.yaml

Added `/usr/share/n98-magerun2/scripts` location.
This helps to facilitate packaged (e.g. RPM) scripts installed to `/usr/share/n98-magerun2/scripts`.

Add scripts location

---

src/N98/Magento/Command/Database/DumpCommand.php

Subject: When mysqldump fails, make db:dump fail as well
As of late, we've been seeing occasional errors like this in the mysqldump command on some specific environments:
```
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `catalogrule_group_website` at row: 0
```
When we perform a `db:dump` command using n98/magerun2 however, it doesn't detect this error and just returns status code 0 which makes it hard for our scripts to detect a failure happened or not.
It looks like support for return codes was already partly added in https://github.com/netz98/n98-magerun2/pull/467 which seems to be the same changes as done in magerun 1: …

When mysqldump fails, make db:dump fail as well

---

config.yaml

Mainly the email_importer was a concern, which can be massive (and contains customer data). 
But also the other tables you do not want to have filled with data when getting a `@development` dump
Fixes # .
- add all dotmailer tables to the dotmailer group

Strip all dotmailer tables

---

README.md
src/N98/Magento/Command/Database/DumpCommand.php

Subject: Checks if current MySQL installation has 'column statistics' present and adds a flag to prevent error.
Fixes #571
- Perform a grep for the term 'column-statistics' on the `mysqldump --help` command output to determine if flag is needed
- Allows user to add an option to `db:dump` command to retain column statistics in the dump if desired
- If no such option is provided, column statistics is disabled to prevent error

Add check to determine whether column statistics flag is needed

---

README.md
src/N98/Magento/Command/Database/DumpCommand.php

- With the release of MySQL 5.7.31 it is necessary to add the --no-tablespace option to the mysqldump command if you want to create a dump without the PROCESS privilege (https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html#mysqld-5-7-31-security)

add option to dump db with —no-tablespaces option

---

config.yaml

A full list of dotmailer tables is available here: https://github.com/dotmailer/dotmailer-magento2-extension/blob/HEAD/Setup/SchemaInterface.php
`email_template` is core Magento and should not be stripped. Ref: https://github.com/magento/magento2/blob/HEAD/app/code/Magento/Email/etc/db_schema.xml#L10
Fixes a bug introduced in #568 (released as version 4.2.0).
- Remove `email_template` from list of tables to be stripped as part of `@dotmailer`

Correct list of 'dotmailer' tables

---

src/N98/Magento/Command/Database/DumpCommand.php

I am not sure how relevant this is here or whether it would be preferable to manage it in the `my.cnf` (or equivalent) like so
```
[mysqld]
set-gtid-purged=OFF
```
Either way, we had our database dumps from prod break all of a sudden when something in the cloud side updated and started adding `SET @@GLOBAL.GTID_PURGED='';` to our dumps which broke importing them locally and on other test systems.
Even if this PR is rejected maybe it will help anyone else using magerun who searches for this issue find a solution.

Add set-gtid-purged-off to db:dump

---

res/twig/dev/module/create/app/code/module/registration.php.twig

Subject: fix PSR-12 violation in the `registration.php`generated by `dev:module:create`
phpcs reports the following PSR-12 violation as follows:
```
$ phpcs --standard=PSR12 app/code/Foo/Bar                                                                                                                       
FILE: /path/to/magento/app/code/Foo/Bar/registration.php
---------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------
3 | ERROR | [x] Import statements must not begin with a leading backslash
----------------------------------------------------------------------------------------------- …
```

Fix PSR-12-violation in the registration.php file generated by dev:module:create

---

res/twig/dev/module/create/app/code/module/Setup/UpgradeData.php.twig
res/twig/dev/module/create/app/code/module/Setup/UpgradeSchema.php.twig

Subject: fix order of import statements in the `Setup` classes generated by `dev:module:create`.
This resolves the following issues:
* Running [Optimize Imports in PhpStorm](https://www.jetbrains.com/help/phpstorm/creating-and-optimizing-imports.html#optimize-imports) resulted in changes to the file (because the imports were ordered alfabetically).
* Running Php_CodeSniffer with the [`SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses` sniff](https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesalphabeticallysorteduses-) gave an error on the files in this PR.

Fix order of import statements in the Setup classes generated by dev:module:create

---

res/autocompletion/bash/n98-magerun2.phar.bash
res/twig/dev/module/create/app/code/module/Setup/InstallData.php.twig
res/twig/dev/module/create/app/code/module/Setup/InstallSchema.php.twig
res/twig/dev/module/create/app/code/module/Setup/UpgradeData.php.twig
res/twig/dev/module/create/app/code/module/Setup/UpgradeSchema.php.twig
res/twig/dev/module/create/app/code/module/registration.php.twig
src/N98/Magento/Command/Developer/Module/CreateCommand.php

Subject: Add `--add-strict-types` option to `dev:module:create` command
This adds the following line to all PHP files that are generated by the command:
```php
declare(strict_types=1);
```
This also makes sure the [SlevomatCodingStandard.TypeHints.DeclareStrictTypes sniff](https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintsdeclarestricttypes-) passes the test.

Add --add-strict-types option to dev:module:create command

---

src/N98/Magento/Command/Database/ImportCommand.php

Add `--force` option to `db:import`
>Continue even if an SQL error occurs
>- https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_force
**Before**
```
$ n98-magerun2 db:import -cgzip ./prod.sql.gz
Import MySQL Database
Importing SQL dump ./prod.sql.gz to database database_name
ERROR 1359 (HY000) at line 7146: Trigger already exists
gzip: error writing to output: Broken pipe
Finished
```
**After**
```
$ n98-magerun2 db:import --force -cgzip ./prod.sql.gz
Import MySQL Database
Importing SQL dump ./baseprod.sql.gz to database database_name
ERROR 1359 (HY000) at line 7146: Trigger already exists
ERROR 1359 (HY000) at line 7164: Trigger already exists
Finished
```

Add --force to db:import

---

src/N98/Magento/Command/Database/ImportCommand.php

Subject: When the mysql import fails, make db:import fail as well
When you try to import an sql file through `db:import` and the sql file has a syntax error or some other error, then the status code from `db:import` was `0` which indicates no errors were seen even though the error is being outputted. This is not correct and scripts using `db:import` won't see the failure and keep running as if everything went fine.
This PR changes this so it has status code `1` when an error occurs during `db:import`.
This is very similar to https://github.com/netz98/n98-magerun2/pull/551 but now for `db:import`
When the `--force` flag is used (introduced in https://github.com/netz98/n98-magerun2/pull/666) the status code remains `0` …

When the mysql import fails, make db:import fail as well

---

src/N98/Util/Console/Helper/DatabaseHelper.php

Subject: db:dump does not support unix socket connection
The db:dump command is using getMysqlClientToolConnectionString which supports unix socket connections, but unfortunately the detectDbSettings is not detecting it in the same way as getConnection. This normalises so that it works correctly in the same way Magento does too.
Code in getConnection that already performs exactly what this PR changes the getMysqlClientToolConnectionString to perform:
https://github.com/netz98/n98-magerun2/blob/23d927e4c54cee2b41a07487d0a17184696c0be6/src/N98/Util/Console/Helper/DatabaseHelper.php#L129-L134
Currently with host set to a socket path, magerun works fine, so does Magento, but magerun db:dump completely fails due to a …

db:dump does not support unix socket connection specified via "host" instead of "unix_socket"

---

config.yaml

Subject: Add `inventory_reservation` table to `@sales` group
The `inventory_reservation` table (from [`magento/module-inventory-reservations`](https://github.com/magento/inventory/blob/1.2.2/InventoryReservations/etc/db_schema.xml#L10)) contains entries that relate to orders (`order_placed`, `shipment_created`, `creditmemo_created`, `order_canceled`, etc). When the order tables are stripped, it makes sense to strip these inventory reservation entries also. If these are not stripped, stock information isn't reliable.

Strip inventory_reservation in @sales group

---

config.yaml

Subject: Add ui_bookmark to admin table group
`ui_bookmark` keeps track of admin sorting and  states of grids - an easy inclusion into `@admin`. See: https://www.pixiemedia.co.uk/blog/magento2-ui-component-bookmarks.html

Add ui_bookmark to admin group

---

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php

If a cron expression has an empty/null value in the store_config_data table then we get an error if we run `sys:cron:run` command.
Fixes: #781

Fix issue with empty cron expressions

---

CHANGELOG.md
src/N98/Magento/Application/AutoloaderDecorator.php

Fixes #789
- Do not mirror PSR-4 prefix of n98-magerun2 autoloader to original Magento autoloader

Do not use n98-magerun2 Composer classes in original Magento autoloader

---

.gitignore
README.md
src/N98/Magento/Command/Config/Env/SetCommand.php
src/N98/Magento/Command/Config/Env/ShowCommand.php
tests/N98/Magento/Command/Config/Env/SetCommandTest.php
tests/N98/Magento/Command/Config/Env/ShowCommandTest.php

Subject: Various changes to the `config:env:*` commands
Fixes https://github.com/netz98/n98-magerun2/issues/766
- Ignores `.phpunit.result.cache` files, this file kept popping up when running unit tests on my local machine
- Fixes a small bug in the `config:env:show` command when you execute it without a key and have something like this in your `env.php` file:
```php
"downloadable_domains" => [
],
```
- Fixes a small bug in the README file where it incorrectly mentioned `config:env:show` [twice](https://github.com/netz98/n98-magerun2/blob/99522042b25d344ff46644e6497d0c06b84d19e7/README.md#show-envphp-settings)
- The big change of this PR: introduces a `--input-format` option for the `config:env:set` command which …

Implement input format json for config env set command

---

.github/workflows/magento_platform_tests.yml

Fixes an issue with actions pulling outdated dependencies.
Now there are two scenarios:
1) For new branches, we might pull a cached vendor folder **without** comparing the composer.lock hash.
We now always run composer install, so composer will update what has changed.
2) For existing branches, we should pull a cached vendor folder **with** comparing the composer.lock hash.
We will now also run composer install, but it will run quickly as there will be nothing to do.
Bonus: If the cache is somehow broken, this is an added gate that will now fail the pipeline and give the system a chance to invalidate the cache.
Before the change, in case 1), we would just pull a probably outdated cached folder from the parent branch and could never recover without manually invalidating caches.

 * upd: always run composer to make sure dependencies are correct

---

README.md
config.yaml
src/N98/Magento/Command/Config/Env/DeleteCommand.php
tests/N98/Magento/Command/Config/Env/DeleteCommandTest.php

Subject: adds a config:env:delete command
I was searching for a command line command to remove Redis cache configurations from the `env.php` file but didn't find any. This has been requested a [couple](https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Disabling-Redis-cache-from-command-line/m-p/89599) of [times](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/Add-support-for-disabling-Redis-cache-from-command-line/idi-p/89789) on the Magento forums, so it looks like this might be helpful to more people 🙂 
This PR adds a way to do this.

Adds a config:env:delete command

---

src/N98/Magento/Command/AbstractMagentoCommand.php

Use Composer helper or guzzle for downloads!
Subject: Remove public methods to removed composer download manager
- Remove methods -> use guzzle for general purpose downloads or `$this->getHelper('composer')` to work with external composer binary.

Remove Composer download methods in abstract command

---

composer.json
composer.lock
src/N98/Magento/Command/Config/Env/CreateCommand.php
src/N98/Magento/Command/Config/Env/DeleteCommand.php
src/N98/Magento/Command/Config/Env/SetCommand.php
src/N98/Magento/Command/Config/Env/ShowCommand.php
src/N98/Magento/Command/System/Check/Env/CheckAbstract.php

Summary: Maintenance of dflydev/dot-access-data seems to be better. We need PHP 8.1 support.
- Remove adbario/php-dot-notation package
- Add dflydev/dot-access-data
- Update config:env commands
- Update sys:check command

Replace dependency "adbario/php-dot-notation" with "dflydev/dot-access-data"

---

src/N98/Magento/Command/Installer/SubCommand/PreCheckPhp.php

Fixes #934
- Check if the function xdebug_is_enabled exists - To allow xdebug ^3.0

Allow for xdebug ^3.0 - check if xdebug_is_enabled function exists

---

.ddev/commands/web/install-magento-ce-git
README.md
config.yaml
src/N98/Magento/Command/Developer/Module/DetectComposerDependenciesCommand.php
tests/phar-test.sh

Summary: Backport of a command used in a netz98 QA suite to migrate modules.
This command scans the code for Composer dependencies and provide a recommendation. It can print only missing dependencies.
Special thanks go to:
- @frostblogNet - Original idea and code
- @a-dite - Mainly developed and tested 
- Provide new command `dev:module:detect-composer-dependencies`

Add new dev:module:detect-composer-dependencies command (netz98 contribution)

---

.github/workflows/magento_platform_tests.yml
.github/workflows/phar_build_and_update.yml
box.json.dist
build.sh

Summary: Add installed.php to phar file
- Add path `vendor/composer/installed.php` to box.json.dist file
- Create the phar file in the Github Actions always with Composer 2

Add composer runtime infos (installed.php) to phar

---

src/N98/Magento/Command/System/Cron/RunCommand.php
src/N98/Magento/Command/System/Cron/ScheduleCommand.php

Summary: Replace deprecated strftime calls
Fixes #969
- Use date function instead of strftime
Reference: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

Replace strftime function calls (#969)

---

config.yaml

Summary: Exclude sequence table data when associated entities are excluded
- Add configuration to exclude data from sequence tables (eg, `sequence_invoice_0`, `sequence_shipment_0`, `sequence_order_1`) when associated data (eg, `sales_invoice`, `sales_shipment`, `sales_order`) has been excluded.

Exclude sequence table data when associated entities are excluded

---

composer.json
composer.lock
src/N98/Magento/Application.php
src/N98/Magento/Application/Magento2Initializer.php
src/N98/Util/PharWrapper.php

Summary: Add error handler for autoloader warnings
Fixes: warnings in some older Magento versions
- Refactor app/bootstrap.php inclusion
- Catch all warnings provided during app/boostrap.php inclusion (only this warnings)
- Restore phar wrapper logic and remove typo3/phar-stream-wrapper package

Add error handler for possible warnings of autoloader

---

src/N98/Util/Exec.php
src/N98/Util/OperatingSystem.php

Summary: Allow use of pipefail where supported
This is related to #929. It doesn't fix it fully, but does make the symptom go away a lot of the time.
This pull request removes the check for "bash compatible" shells, relying on the actual feature check for the feature we want to use.
We use docker heavily, and in our set-up, when we run PHP commands there is no `SHELL` environment variable, so the "is this shell bash-compatible" check does not pass. Removing this check allows the `pipefail` feature detection to actually work. I've tested this with shells that do and do not support the feature, and the existing feature detection responds as expected. We're having trouble where command failures aren't being detected in …

Allow use of pipefail where supported

---

config.yaml

* The table caches the configuration and might leak confidential
data, for example if such data is kept in env.php
- [-] README.md reflects changes (if any)
- [-] phar fuctional test (in tests/phar-test.sh)
Fixes #957

#957 Exclude system_config_snapshot from stripped dumps

---

src/N98/Magento/Command/Cache/ListCommand.php

from logging in gh-actions:
PHP Fatal error:  Uncaught TypeError: Return value of "N98\Magento\Command\Cache\ListCommand::execute()" must be of the type int, "null" returned. in /home/runner/work/n98-magerun2/n98-magerun2/magento/vendor/symfony/console/Command/Command.php:301
Stack trace:
#0 phar:///home/runner/work/n98-magerun2/n98-magerun2/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(249): Symfony\Component\Console\Command\Command->run()
#1 phar:///home/runner/work/n98-magerun2/n98-magerun2/n98-magerun2.phar/src/N98/Magento/Command/Cache/AbstractModifierCommand.php(33): N98\Magento\Command\AbstractMagentoCommand->run()
#2 phar:///home/runner/work/n98-magerun2/n98-magerun2/n98-magerun2.phar/src/N98/Magento/Command/Cache/AbstractModifierCommand.php(67): …

Return integer 0 on Cache-ListCommand

---

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php

Fixes #1028
Sometimes the job config is empty. In this case we have to fix initialize the jonconfig in the getSchedule method.

Check if job config is set

---

.github/workflows/pr-artifacts-comment.yml

Copied from ddev project
Add a new workflow which runs after the "PR Build" workflow. If the "PR Build" was able to create phar files as artifact then this workflow will run and add a comment with links to the files.

Add workflow to create a comment witj links to PR artifacts

---

CHANGELOG.md
src/N98/Magento/Application.php

- Do not try to detect Magento root directory if self-update command should be run
- Prevent custom config loading for self-update
- Do not detect Magento version for self-update

Do not load config or init Magento for self-update

---

src/N98/Magento/Application.php
src/N98/Magento/Application/MagentoCoreCommandProvider.php

- Skip loading of core commands if their is an error in Magento but provide n98-magerun2 commands.

Catch errors if command list cannot be loaded from core magento

---

.php-cs-fixer.php
composer.json
composer.lock
src/N98/Magento/Application/AutoloaderDecorator.php
src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php
src/N98/Magento/Command/Cache/ListCommand.php
src/N98/Magento/Command/Customer/DeleteCommand.php
src/N98/Magento/Command/Integration/ListCommand.php
src/N98/Magento/Command/MagentoCoreProxyCommand.php
src/N98/Magento/Command/ScriptCommand.php
src/N98/Magento/Command/System/Url/ListCommand.php

Summary: Update php-cs-fixer to ^3.9
Fixes #1111 (by updating a dependency)
- Update php-cs-fixer depedency
- Indirect depenrency update of composer/xdebug-handler which updates composer/pcre which fixes #1111
- Fix violations
- Remove php-cs-fixer config deprecations

Update php-cs-fixer to 3.9 and fix new violations

---

src/N98/Magento/Command/MagentoCoreProxyCommand.php

Fixes #1149
- Use the defined PHP binary for every call to bin/magento

Use defined PHP binary for calls to bin/magento (#1149)

---

README.md
config.yaml
src/N98/Magento/Command/Sales/SequenceAddCommand.php
src/N98/Magento/Command/Sales/SequenceRemoveCommand.php

+ add sequences
+ remove sequences
somethings the store_add trigger is not always triggered for whatever reason, this makes it possible to create them.
Related Stack Overflows, issues, etcetera:
- https://magento.stackexchange.com/a/149280
- https://github.com/magento/magento2/issues/12318
Fixes # .
- ...
- ...
- ...

Added 2 new commands to manage sales sequences

---

CHANGELOG.md
src/N98/Magento/Application.php

Also relates to #1164
- Add debug output if `bin/magento` is broken

Add a way to debug errors of bin/magento

---

res/twig/dev/console/make/module/composer.json.twig
src/N98/Magento/Command/Developer/Console/MakeModuleCommand.php
src/N98/Magento/Command/Developer/Module/DetectComposerDependenciesCommand.php
src/N98/Util/ComposerLock.php
tests/N98/Util/ComposerLockTest.php

Introduces a abstraction to read data of composer.lock. Use current php version and actual installed version of magento/framework as version of dependencies for new generated module.
- Introduce new ComposerLock abstraction
- Use ComposerLock in dependency check command
- Process new variables in twig templates of make:module dev console command

Automatic php version and framework dependency detection

---

src/N98/Magento/Command/Config/Store/GetCommand.php
tests/N98/Magento/Command/Config/Store/GetCommandTest.php

I find this useful to see straight away when looking at the config
```
$ ./bin/n98-magerun2 --root-dir=/Users/lukerodgers/src/project config:store:get 'tax/cart_display/zero_tax'
+---------------------------+---------+----------+-------+---------------------+
| Path                      | Scope   | Scope-ID | Value | Updated At          |
+---------------------------+---------+----------+-------+---------------------+
| tax/cart_display/zero_tax | default | 0        | 1     | 2022-03-03 09:01:59 |
| tax/cart_display/zero_tax | stores  | 1        | 0     | 2022-03-03 19:10:12 |
| tax/cart_display/zero_tax | stores  | 5        | 0     | 2022-03-03 19:10:26 |
| tax/cart_display/zero_tax | stores  | 8        | 0     | 2022-03-03 19:10:20 |
| tax/cart_display/zero_tax | stores  | 9        | 0 …
```

Add `Updated At` to `config:store:get` output

---

CHANGELOG.md
src/N98/Magento/Command/Generation/FlushCommand.php

- Check return status of `\N98\Util\Filesystem::recursiveRemoveDirectory`
- Print error message if directory cannot be removed

Make errors visisble in generation:flush command

---

CHANGELOG.md
src/N98/Magento/Command/Cache/ViewCommand.php
tests/phar-test.sh

Fixes #1254
- Add decrypt option
- Use Magento standard Decryptor

Add decrypt option to cache:view command

---

.ddev/config.yaml
README.md
config.yaml
src/N98/Magento/Command/Cache/CatalogImageFlushCommand.php
tests/bats/functional_magerun_commands.bats

Fixes #1192
- Add new command to clear the catalog product images cache
- Add option to suppress the event dispatching
- Add N98_MAGERUN2_BIN variable to ddev environment

Clear media cache command

---

.github/workflows/magento_platform_tests.yml
config.yaml

This PR implement Magento 2 version 2.4.6-p2 in build.yml to allow installation of this version with n98

Adding Magento 2.4.6-p2

---

src/N98/Magento/Command/Integration/DeleteCommand.php

Fixes #1287
- Inject `Magento\Integration\Api\OauthServiceInterface` in command class
- Call `Magento\Integration\Api\OauthServiceInterface::deleteConsumer`

Delete oauth consumer entry on integration:delete (#1287)

---

.markdown-lint.yml
README.md
config.yaml
src/N98/Magento/Command/MagentoCoreProxyCommand.php

Filter of env variables for the`bin/magento` calls via proxy command:
- 'PHP_IDE_CONFIG',
-   'PHP_OPTIONS',
-   'XDEBUG_CONFIG',
-   'XDEBUG_SESSION',
-   'XDEBUG_SESSION_START',
-   'XDEBUG_TRACE',
-   'XDEBUG_PROFILE'

Filter all debug related variable in proxy calls (#1240)

---

src/N98/Magento/Command/MagentoCoreProxyCommand.php

Related to #1295
- Register the right shortcut of core commands instead of the option name

Fix short options registration of core commanda (#1295)

---

.github/workflows/magento_platform_tests.yml
config.yaml

- Rename old mage-os config entries and prefix them with "mageos-magento-mirror" to distinguish between the mage-os release and the Magento mirror.
- Add Mage-OS 1.0.0 release to installer
- - Add Mage-OS 1.0.0 release regular platform check

Add mage-os 1.0.0 to build and config

---

src/N98/Magento/Command/MagentoCoreProxyCommand.php

If a Magento Core command is started by a proxy command in n98-magerun2 we did not respect the stdout/stderr.
The PR mirrors the stdout and stderr.

Write errors of proxy command to stderr

---

.github/workflows/deploy.yml

We should trust our own key in the deployment process.

Try own GPG key after the import

---

src/N98/Magento/Application/MagentoDetector.php

If no root dir could be detected, try to use
the current directory of the phar file instead.
Summary: Added additional check for root directory as fallback in `\N98\Magento\Application\MagentoDetector` class.
Related to #1305
Has to be tested very good.

Use phar file path as fallback

---

README.md
src/N98/Magento/Command/Database/DumpCommand.php

Summary: 
Even when magerun db dump command is executed with _--only-command_ option a piped definer replacement is added to its output. In some scenarios it is a bit not intuitive or undesirable, e.g. when dump is imported on the same database or _--only-command_ output is further processed in separate script. 
- Added flag _keep-definer_ to allow a pure mysql command to be outputted or executed.

Make SQL definer replacement optional

---

.php-cs-fixer.php
src/N98/Magento/Command/Customer/DeleteCommand.php

Currently the delete option is confusing and has to be combined with a filter.
If someone wants to delete all customers we do not need any filter.
Related to: #1359
Refactoring of  `customer:delete` command.
- Allow to specify the `--all` option without any filter option.
- Combine the `--all` flag with `--force` flag.
- Remove `--all` check in filters

The delete option should work only without filters (#1359)

---

src/N98/Magento/Command/MagentoCoreProxyCommand.php

Related to #1397
hanges proposed in this pull request:
Add additional `escapeshellcmd` before the Symfony StringInput removes the quotes

Escape shell command before processing by Symfony StringInput (#1396)

---

src/N98/Magento/Command/MagentoCoreProxyCommand.php

The PHP binary path can contain spaces which cause issues.
Related to #1406 
Modify MagentoCoreProxyCommand and use the PHP function `escapeshellarg` to quote the path to
the PHP binary and bin/magento.
The following arguments should already be quoted by the Symfony command logic.

Quotes all arguments used by MagentoCoreProxyCommand (#1406)

---

.github/workflows/magento_platform_tests.yml
config.yaml

- Add Magento 2.4.6-p4 and 2.4.5-p6 to installer
- Add PHP 8.2 test setup

Add new Magento versions to installer and test setup

---

README.md
src/N98/Magento/Command/Developer/Module/ListCommand.php

Related to #1422
- Add module status (enabled, disabled) as new column
- Add new option `--only-enabled`
- Add new option `--only-disabled`

Add module status to dev:module:list command

---

.github/workflows/magento_platform_tests.yml
.github/workflows/php-code-style.yml

- Remove php-cs-fixer check from platform tests
- Check code style in a separate workflow

Move php-cs-fixer checks to own workflow

---

src/N98/Magento/Command/Developer/Module/DetectComposerDependenciesCommand.php

Related to #1358
- Strip patch level in output of recommended versions

Remove patch level in recommended version

---

src/N98/Magento/Command/Developer/DecryptCommand.php

Fixed a typo in the class name
Fixed typo, so composer's optimised autoloader no longer complains:
```
$ composer dump-autoload -o
Generating optimized autoload files
Class N98\Magento\Command\Developer\decryptCommand located in ./src/N98/Magento/Command/Developer/DecryptCommand.php does not comply with psr-4 autoloading standard (rule: N98\ => ./src/N98). Skipping.
...
```

Fixed casing of DecryptCommand class

---

.ddev/config.yaml
.ddev/docker-compose.elastic.yaml
.ddev/docker-compose.magento-volumes.yaml
src/N98/Magento/Command/Database/DumpCommand.php
src/N98/Util/Console/Helper/DatabaseHelper.php

Summary: The client tools provided by MariaDB are not the same as the MySQL client tools. One difference is the missing `mysqldump --ssl-mode` parameter
Fixes #1526 
Added a check which calls mysqldump help and grep the output for `--ssl-mode` option. If the option does not exist, we do not add the option to the connection string used in the `db:dump` and `db:import` command.

Some mariadb client tools does not support ssl-mode option

---

README.md
config.yaml
src/N98/Magento/Command/Developer/Di/Preference/ListCommand.php
src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php
tests/N98/Magento/Command/Developer/Di/Preference/ListCommandTest.php
tests/bats/functional_magerun_commands.bats

Related to #85
- Add graphql area to observer list command
- Add new command to list di preferences by area

dev:di:preferences:list command

---

README.md
src/N98/Magento/Command/Database/DumpCommand.php
tests/N98/Magento/Command/Database/DumpCommandTest.php

Magento databases can be quite unwieldy. Several gigabytes is not an exception. Dumping and importing these can take considerable time. There's a great tool called [mydumper](https://mydumper.github.io/mydumper/docs/html/index.html) which also includes myloader for dumping & importing databases. These dump & import databases twice as fast as the traditional mysql/mysqldump combo.
However, dumps created by mysqldump cannot be imported using myloader. They needed to be dumped with mydumper in the first place.
For our preview environments for our feature branches, we use a development (or anonimized) dump created by magerun2, so we can't use mydumper/myloader right now.
In this PR, I added support for mydumper to the …

Add mydumper feature to DumpCommand

---

.github/workflows/mage-os_nightly_test.yml

- Update platform dependencies for Mage-OS nightly build
- Move test from Elasticsearch to Openseach
- Use MariaDB instread of MySQL
- Use latest Composer version
- Increase PHP version to 8.3

build: update deps to the latest requirements of Mage-OS

---

README.md
src/N98/Magento/Command/System/Store/Config/BaseUrlListCommand.php
tests/bats/functional_magerun_commands.bats

Summary: Extends the `sys:store:config:base-url:list` command by adding url for the admin store
Fixes possible #1545
- add new option `--with-admin-store` to add the store with ID 0 to the list
- add new option `--with-admin-login-url` to print the whole URL of store 0 appended by admin login url

feat: add new options to display admin store urls

---

README.md
src/N98/Magento/Command/Github/PatchFileContent/Creator.php
src/N98/Magento/Command/Github/PatchFileContent/Processor/AppCodeProcessor.php
src/N98/Magento/Command/Github/PatchFileContent/Processor/AppDesignProcessor.php
src/N98/Magento/Command/Github/PatchFileContent/Processor/I18nProcessor.php
src/N98/Magento/Command/Github/PatchFileContent/Processor/LibProcessor.php
src/N98/Magento/Command/Github/PatchFileContent/Processor/ProcessorInterface.php
src/N98/Magento/Command/Github/PullRequestCommand.php
tests/N98/Magento/Command/Github/PatchFileContent/CreatorTest.php
tests/N98/Magento/Command/Github/PatchFileContent/Processor/AppCodeProcessorTest.php
tests/N98/Magento/Command/Github/PatchFileContent/Processor/AppDesignProcessorTest.php
tests/N98/Magento/Command/Github/PatchFileContent/Processor/I18nProcessorTest.php
tests/N98/Magento/Command/Github/PatchFileContent/Processor/LibProcessorTest.php

Summary: Add new option to apply a patch file directly
Fixes #1594 and #1622
- Add new option `--apply`
- Fix changed vendor name if patch origin is the Mage-OS repository

feat: apply github patch directly

---

.github/workflows/magento_platform_tests.yml
.github/workflows/pr_build.yml
build.sh

I've standardized the PHP and Composer versions used for building and testing the PHAR within the magento_platform_tests.yml workflow.
Changes:
These changes aim to resolve failures in the Magento Platform Tests GitHub Action by ensuring the PHAR is built and tested in an environment consistent with the rest of the matrix job's setup, reducing potential incompatibilities.
- I modified the "Setup PHP for phar build" step in .github/workflows/magento_platform_tests.yml to use `matrix.php-version` and `matrix.composer-version` instead of hardcoded PHP 8.2 and Composer v2. This ensures consistency with the PHP/Composer versions used for Magento installation and initial PHPUnit tests within each matrix job.
- The …

Fix(actions): Standardize PHP/Composer in magento_platform_tests

---

src/N98/Magento/Command/Developer/Console/Shell.php
src/N98/Util/Http/DownloadException.php

This commit addresses deprecation warnings identified by PHPCompatibility and PHPStan related to implicitly nullable parameters. In PHP 8.4, implicitly marking a parameter as nullable by providing a default null value without using the explicit '?' nullable type hint will be deprecated.
The following changes were made:
- In `src/N98/Util/Http/DownloadException.php`:
- The `$previous` parameter in the `__construct` method is now explicitly nullable (`?Throwable`).
- In `src/N98/Magento/Command/Developer/Console/Shell.php`:
- The `$input` parameter in the `run` method is now explicitly nullable (`?InputInterface`).
- The `$output` parameter in the `run` method is now explicitly nullable (`?OutputInterface`).
These changes ensure that the codebase remains compatible with upcoming PHP …

Fix: Make parameters explicitly nullable for PHP 8.4 compatibility

---

docs/docs/extending/configuration.md

Added a hint to the `magerun:config:info` and magerun:config:dump commands to the documentation page "docs/docs/extending/configuration.md". These commands are useful for debugging configuration changes.
Also added links to the documentation for `magerun:config:show`, `magerun:config:info`, and `magerun:config:dump` commands.

docs: add hint and links for config commands

---

docs/docs/extending/development/modules/index.md
docs/docs/extending/development/modules/structure.md

I've added a tip admonition to the module structure page with a link to the n98-magerun2 example module. This provides you with a practical example of a module structure.

docs: add tip admonition to module structure page

---

.github/workflows/deploy.yml

This commit addresses several linting issues identified in the .github/workflows/deploy.yml file:
- **Shellcheck SC2086:** Variables ($GITHUB_OUTPUT) in the 'Set release type' step of the 'create-github-release' job are now double-quoted to prevent globbing and word splitting issues.
- **Yamllint line length:** Long lines were reformatted to be under the 80-character limit. This involved breaking down long commands and strings using YAML block scalars.
- **Yamllint bracket spacing:** Extra spaces within ${{ ... }} expressions were removed for consistency and to adhere to linting best practices.

Fix linting issues in deploy.yml

---

docs/docs/command-docs/routes/index.md

The sidebar label for the Route command group in the static documentation was 'Routes'. This commit changes it to 'Route Commands' to be consistent with other command group labels.

Fix: Correct sidebar label for Route Commands in documentation

---

.github/workflows/mage-os_nightly_test.yml
CHANGELOG.md
src/N98/Util/Console/Helper/DatabaseHelper.php
tests/bats/functional_magerun_commands.bats

Improve db port validation for mysql client tool,

fix(db): improve port handling in DatabaseHelper

---

CHANGELOG.md
src/N98/Magento/Command/Developer/Log/SizeCommand.php

fix the `--filter` opion in `dev:log:size` command.

fix(command): improve log file filtering in dev:log:size command
